import { WandSparkles } from 'lucide-react'
import { useAICrafterStore } from '../store/useAICrafterStore'

function generateLocalComponent(prompt) {
  const lowerPrompt = prompt.toLowerCase()

  if (lowerPrompt.includes('dashboard')) {
    return `export default function App() {
  const cardStyle = {
    background: "#ffffff",
    borderRadius: "12px",
    padding: "16px",
    boxShadow: "0 8px 20px rgba(0,0,0,0.08)"
  };

  return (
    <main style={{ padding: "24px", fontFamily: "Inter, sans-serif", background: "#f1f5f9", minHeight: "100vh" }}>
      <h1 style={{ marginTop: 0 }}>Sales Dashboard</h1>
      <p style={{ color: "#475569" }}>Simple dashboard generated in offline AI mode.</p>
      <section style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "12px" }}>
        <article style={cardStyle}><h3>Total Revenue</h3><p>$124,000</p></article>
        <article style={cardStyle}><h3>New Customers</h3><p>342</p></article>
        <article style={cardStyle}><h3>Conversion Rate</h3><p>6.4%</p></article>
      </section>
    </main>
  );
}`
  }

  if (lowerPrompt.includes('pricing')) {
    return `export default function App() {
  const plans = [
    { name: "Starter", price: "$19", features: ["1 project", "Basic support"] },
    { name: "Pro", price: "$49", features: ["10 projects", "Priority support"] },
    { name: "Enterprise", price: "$99", features: ["Unlimited", "Dedicated manager"] }
  ];

  return (
    <main style={{ padding: "24px", fontFamily: "Inter, sans-serif" }}>
      <h1 style={{ textAlign: "center" }}>Pricing Plans</h1>
      <section style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "14px" }}>
        {plans.map((plan) => (
          <article key={plan.name} style={{ border: "1px solid #d1d5db", borderRadius: "12px", padding: "16px" }}>
            <h2>{plan.name}</h2>
            <p style={{ fontSize: "1.6rem", fontWeight: 700 }}>{plan.price}</p>
            <ul>{plan.features.map((item) => <li key={item}>{item}</li>)}</ul>
            <button style={{ marginTop: "8px", padding: "8px 12px" }}>Choose Plan</button>
          </article>
        ))}
      </section>
    </main>
  );
}`
  }

  return `export default function App() {
  return (
    <main style={{ padding: "24px", fontFamily: "Inter, sans-serif" }}>
      <h1>Generated Component</h1>
      <p>This component is generated by local offline AI logic.</p>
      <p><strong>Your prompt:</strong> ${JSON.stringify(prompt)}</p>
      <button style={{ marginTop: "10px", padding: "8px 14px", borderRadius: "8px" }}>
        Action Button
      </button>
    </main>
  );
}`
}

function improveLocalComponent(existingCode, improvePrompt) {
  const lowerImprovePrompt = improvePrompt.toLowerCase()
  let nextCode = existingCode

  if (lowerImprovePrompt.includes('dark')) {
    nextCode = nextCode.replace('fontFamily: "Inter, sans-serif"', 'fontFamily: "Inter, sans-serif", color: "#e2e8f0", background: "#0f172a", minHeight: "100vh"')
  }

  if (lowerImprovePrompt.includes('animation')) {
    nextCode += '\n\n// Tip: Add CSS keyframes in your real project for richer animation.'
  }

  if (lowerImprovePrompt.includes('button') && !nextCode.includes('Action Button')) {
    nextCode = nextCode.replace('</main>', '  <button style={{ marginTop: "12px", padding: "8px 12px" }}>Action Button</button>\n    </main>')
  }

  return nextCode
}

export function PromptPanel() {
  const {
    prompt,
    improvePrompt,
    generatedCode,
    isLoading,
    setPrompt,
    setImprovePrompt,
    setGeneratedCode,
    setStatusMessage,
    setIsLoading,
  } = useAICrafterStore()

  async function handleGenerate() {
    if (!prompt.trim()) {
      setStatusMessage('Please enter a component prompt first.')
      return
    }

    try {
      setIsLoading(true)
      setStatusMessage('Generating component in offline AI mode...')
      await new Promise((resolve) => setTimeout(resolve, 450))
      const code = generateLocalComponent(prompt)
      setGeneratedCode(code)
      setStatusMessage('Component generated. Check the live preview.')
    } catch (error) {
      setStatusMessage(error instanceof Error ? error.message : 'Something went wrong.')
    } finally {
      setIsLoading(false)
    }
  }

  async function handleImprove() {
    if (!improvePrompt.trim()) {
      setStatusMessage('Write what to improve first.')
      return
    }

    try {
      setIsLoading(true)
      setStatusMessage('Improving component in offline AI mode...')
      await new Promise((resolve) => setTimeout(resolve, 450))
      const code = improveLocalComponent(generatedCode, improvePrompt)
      setGeneratedCode(code)
      setStatusMessage('Component improved. Preview updated.')
    } catch (error) {
      setStatusMessage(error instanceof Error ? error.message : 'Something went wrong.')
    } finally {
      setIsLoading(false)
    }
  }

  function useExamplePrompt(value) {
    setPrompt(value)
    setStatusMessage('Example prompt added. Click Generate Component.')
  }

  return (
    <section className="card">
      <h2>AI Prompt Panel</h2>
      <p className="label" style={{ marginTop: 0 }}>
        Offline Fake AI Mode (No API key needed)
      </p>

      <label className="label">Component Prompt</label>
      <textarea
        value={prompt}
        onChange={(event) => setPrompt(event.target.value)}
        rows={5}
        placeholder="Create a modern pricing section with 3 cards and a CTA button."
      />
      <div className="exampleRow">
        <button type="button" className="tagButton" onClick={() => useExamplePrompt('Create a dashboard with 3 metric cards and a top header.')}>
          Dashboard
        </button>
        <button type="button" className="tagButton" onClick={() => useExamplePrompt('Create a pricing page with 3 plans and CTA button.')}>
          Pricing
        </button>
        <button type="button" className="tagButton" onClick={() => useExamplePrompt('Create a modern hero section with heading and signup button.')}>
          Hero
        </button>
      </div>
      <button className="primaryButton" type="button" onClick={handleGenerate} disabled={isLoading}>
        <WandSparkles size={16} />
        {isLoading ? 'Generating...' : 'Generate Component'}
      </button>

      <label className="label">Improve Existing Code</label>
      <textarea
        value={improvePrompt}
        onChange={(event) => setImprovePrompt(event.target.value)}
        rows={3}
        placeholder="Add dark mode toggle and smooth hover animation."
      />
      <button className="secondaryButton" type="button" onClick={handleImprove} disabled={isLoading}>
        Improve With AI
      </button>
    </section>
  )
}
